env:
  browser: true
  es2021: true
extends: google
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-tabs: warn
  camelcase: warn
  indent: warn
  no-var: warn
  quotes: warn
  no-trailing-spaces: warn
  no-mixed-spaces-and-tabs: warn
  comma-dangle: warn
  spaced-comment: warn
  keyword-spacing: warn
  eol-last: warn
  space-before-blocks: warn
  brace-style: warn
  max-len: warn
  padded-blocks: warn
  linebreak-style: warn