name: rM-APIGEE-Connector-Deploy
on:
  workflow_call:
    inputs:
      apigee-environment:
        type: string
        required: true
        description: 'To Get APIGEE environment to deploy Connector'
    outputs:
      job-status: 
        value: ${{ jobs.Deploy-Connector-To-APIGEE.result }}
      step-status:
        value: ${{ jobs.Deploy-Connector-To-APIGEE.outputs.step-status }}
jobs: 
  Deploy-Connector-To-APIGEE:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    environment: ${{ inputs.apigee-environment }}  
    outputs:
      step-status: ${{ steps.deploy-connector.outcome }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Authenticate with GCP using WFI
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}
          token_format: 'access_token'
      - name: Install IntegrationCLI
        run: |
          curl -L https://raw.githubusercontent.com/GoogleCloudPlatform/application-integration-management-toolkit/main/downloadLatest.sh | sh -
          echo "/home/runner/.integrationcli/bin" >> $GITHUB_PATH
      - name: Deploy Connectors
        id: deploy-connector
        run: |
            echo "Created New connectors in ${{ vars.GCP_PROJECT }}"
            integrationcli connectors import -t=${{ steps.auth.outputs.access_token }} -p=${{ vars.GCP_PROJECT }} -r=${{ vars.GCP_REGION }} -f="connectors" --wait

            echo "Avaiable connectors in ${{ vars.GCP_PROJECT }}"
            integrationcli connectors list -t=${{ steps.auth.outputs.access_token }} -p=${{ vars.GCP_PROJECT }} -r=${{ vars.GCP_REGION }}