name: rM-APIGEE-KVM-Pipeline
run-name: ${{ github.actor }} ran pipeline for APIGEE KVM values deployment.
on:
  workflow_call:
    inputs:
      apigee-environment:
        type: string
        required: true
        description: 'To Get APIGEE environment to deploy proxy'
jobs:
  Notify_On_Slack_for_approval:
    uses: ./.github/workflows/Notify-On-Slack.yml
    with:
      workflow_status: Awaiting for Reviewer Approval
    secrets: inherit
  
  Call_Dev_Reusable_workflow:
    needs: Notify_On_Slack_for_approval
    if: inputs.apigee-environment == 'development'
    uses: ./.github/workflows/KVM-Deploy.yml
    with:
      apigee-environment: development
    secrets: inherit    

  Call_Staging_Reusable_workflow:
    needs: Notify_On_Slack_for_approval
    if: inputs.apigee-environment == 'staging'
    uses: ./.github/workflows/KVM-Deploy.yml
    with:
      apigee-environment: staging
    secrets: inherit

  Call_Production_Reusable_workflow:
    needs: Notify_On_Slack_for_approval
    if: inputs.apigee-environment == 'production'
    uses: ./.github/workflows/KVM-Deploy.yml
    with:
      apigee-environment: production
    secrets: inherit
  
  Notify_Workflow_Status_On_Slack:
    if: always()
    needs: [Call_Staging_Reusable_workflow, Call_Production_Reusable_workflow, Call_Dev_Reusable_workflow ]
    uses: ./.github/workflows/Notify-On-Slack.yml
    with:
      workflow_status: ${{needs.Call_Dev_Reusable_workflow.outputs.step-status}}${{needs.Call_Production_Reusable_workflow.outputs.step-status}}${{ needs.Call_Staging_Reusable_workflow.outputs.step-status }}
    secrets: inherit