name: rM-APIGEE-Slack-Notify
on:
    workflow_call:
      inputs:
        workflow_status:
          type: string
          required: true
          description: 'To post status of workflow'
jobs:
    Notify_On_Slack:
        runs-on: ubuntu-latest
        steps:
          - name: Notify On Slack
            id: slack-notifications
            uses: slackapi/slack-github-action@v1.25.0
            with:
              payload: |
                {
                  "Who":"Deployment: CICD Pipeline for deployment of ${{ github.repository}}.\nWorkflow Name: ${{ github.workflow }}\nWho Initiated: ${{ github.triggering_actor }}\nAPIGEE Envionment: ${{ github.base_ref }}\nPull Request: https://github.com/${{ github.repository}}/pull/${{ github.event.pull_request.number }}",
                  "Status":"Pipline Execution Status: ${{ inputs.workflow_status }}",
                  "URL": "\nhttps://github.com/${{ github.repository}}/actions/runs/${{ github.run_id}}",
                  "Channel": "C05PXKMP0NS"
                }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}